version: '3'

services:
  grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    networks:
      - monitoring
    depends_on:
      - prometheus

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
