global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my_flask_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
    scheme: 'https'
